package org.softserve.academy.provider;

import org.junit.jupiter.api.extension.ExtensionContext;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.ArgumentsProvider;

import java.util.stream.Stream;

public class InvalidEmailProvider
        implements ArgumentsProvider {
    @Override
    public Stream<? extends Arguments> provideArguments(ExtensionContext context) {
        return Stream.of(
                Arguments.of("abc@icom"),
                Arguments.of(".abc@i.com"),
                Arguments.of("abc@i.c1om"),
                Arguments.of("ab@c.d"),
                Arguments.of("a@b.c"),
                Arguments.of("@i.com"),
                Arguments.of("abc.@i.com"),
                Arguments.of("abc@i.c"),
                Arguments.of("abc@.com"),
                Arguments.of("abc@i"),
                Arguments.of("abc@domain@com"),
                Arguments.of(".abc@i.com"),
                Arguments.of("abc@domain.c1om"),
                Arguments.of("abc@domain.a"),
                Arguments.of("ab@c.d"),
                Arguments.of("longemail.@i.ua"),
                Arguments.of("123longemail.@i.com"),
                Arguments.of("longemail123.@i.com"),
                Arguments.of("email..email@i.com"),
                Arguments.of("email...email@i.com"),
                Arguments.of(" "),
                Arguments.of(""),
                Arguments.of("a@b.c"),
                Arguments.of(" @.ua"),
                Arguments.of(" @i.ua"),
                Arguments.of("a@ .ua"),
                Arguments.of("email@"),
                Arguments.of("email@u"),
                Arguments.of("email.com"),
                Arguments.of("email@i.u"),
                Arguments.of("email@1i.u"),
                Arguments.of("email@i..u"),
                Arguments.of("email@.com"),
                Arguments.of(",email@i.com"),
                Arguments.of("@email@i.com"),
                Arguments.of("a@email@i.com"),
                Arguments.of("email@.com"),
                Arguments.of("@email.com"),
                Arguments.of("email@.com."),

//                Arguments.of("1234567890@host.com"),
//                Arguments.of("1abc@i.com"),
//                Arguments.of("abc!@i.com"),
//                Arguments.of("1abc@i.com"),
//                Arguments.of("abc@i1.com"),
//                Arguments.of("abc@doma1n.com"),
//                Arguments.of("a@b.co"),
//                Arguments.of("abcdeabcdeabcdeabcdea@domain.com"),
//                Arguments.of("1email@.com."),
//                Arguments.of("1mail@i.ua"),
//                Arguments.of("mail1@i.ua"),
//                Arguments.of("now.1@i.ua"),
//                Arguments.of("!email@i.com"),
//                Arguments.of("e@i.ua"),
//                Arguments.of("+email@i.com"),
//                Arguments.of("-email@i.ua"),
//                Arguments.of("&email@i.ua"),
//                Arguments.of("*email@i.ua"),
//                Arguments.of("_email@i.ua"),
//                Arguments.of("+email@i.ua"),
//                Arguments.of("email@1.ua"),
//                Arguments.of("email@11.ua"),
//                Arguments.of("123@i.ua"),
//                Arguments.of("email@-i.com"),
//                Arguments.of("email+tag@i.com"),
//                Arguments.of("email@i-.com"),
//                Arguments.of("_______@i.com"),
//                Arguments.of("email@-i.com"),
//                Arguments.of("email@i-.com"),
//                Arguments.of("email+@i.ua"),
//                Arguments.of("email&@i.ua"),
//                Arguments.of("email*@i.ua"),
//                Arguments.of("email_@i.ua"),
//                Arguments.of("email@i.12"),
//                Arguments.of("!email@i.ua"),
//                Arguments.of("#email@i.ua"),
//                Arguments.of("$email@i.ua"),
//                Arguments.of("%email@i.ua"),
//                Arguments.of("^email@i.ua"),
//                Arguments.of("=email@i.ua"),
//                Arguments.of("{email@i.ua"),
//                Arguments.of("}email@i.ua"),
                
                Arguments.of("@email@i.ua"),
                Arguments.of(")email@i.ua"),
                Arguments.of("[email@i.ua"),
                Arguments.of("]email@i.ua"),
                Arguments.of(",email@i.ua"),
                Arguments.of("<email@i.ua"),
                Arguments.of(".email@i.ua"),
//                Arguments.of("/email@i.ua"),
//                Arguments.of("|email@i.ua"),
//                Arguments.of("'email@i.ua"),
//                Arguments.of("\nemail@i.ua"),
//                Arguments.of("email/@i.ua"),
//                Arguments.of("email|@i.ua"),
                Arguments.of(">email@i.ua"),
                Arguments.of(":email@i.ua"),
                Arguments.of("\"email@i.ua"),
                Arguments.of("\temail@i.ua"),
                Arguments.of(":email@i.ua"),
                Arguments.of(";email@i.ua"),
                Arguments.of(":email@i.ua"),
                Arguments.of("user123@i.i123"),
//                Arguments.of("email'@i.ua"),
//                Arguments.of("user-123@i.com"),
//                Arguments.of("user_123@i.com"),
//                Arguments.of("firstname+lastname@i.com"),
//                Arguments.of("firstname-lastname@i.com"),
//                Arguments.of("verylongemailaddresswithmorethan30charactersinlocalpart@i.com"),
//                // Invalid: Username with short length
//                Arguments.of("email!@i.ua"),
//                Arguments.of("email$@i.ua"),
//                Arguments.of("email%@i.ua"),
//                Arguments.of("email^@i.ua"),
//                Arguments.of("email=@i.ua"),
//                Arguments.of("email{@i.ua"),
//                Arguments.of("email}@i.ua"),
//                Arguments.of("email#@i.ua"),
                Arguments.of("email[@i.ua"),
                Arguments.of("email]@i.ua"),
                Arguments.of("email,@i.ua"),
                Arguments.of("email)@i.ua"),
                Arguments.of("email<@i.ua"),
                Arguments.of("email:@i.ua"),
                Arguments.of("email>@i.ua"),
                Arguments.of("email\t@i.ua"),
//                Arguments.of("email\n@i.ua"),
                Arguments.of("email:@i.ua"),
                Arguments.of("email;@i.ua"),
                Arguments.of("email:@i.ua"),
                Arguments.of("email@@i.ua"),
                Arguments.of("email 123@i.ua"),
                Arguments.of("email.email@com"),
                Arguments.of("email.email@ex.c"),
                Arguments.of("email.email@.com"),
                Arguments.of("email.i.com"),
                Arguments.of(".email@i.com"),
                Arguments.of("email email@i.com"),
                Arguments.of("email@127.0.0.1"),
                Arguments.of("email@i"),
                Arguments.of("email@i..com"),
                Arguments.of("Abc..123@i.com"),
                Arguments.of("email@123.123.123.123"),
                Arguments.of("email@111.222.333.44444"),
//                Arguments.of("email@[123.123.123.123]"),
                Arguments.of("email@.com"),
                Arguments.of("email@i."),
                Arguments.of("email@i..com"),
                Arguments.of(".email@i.com"),
                Arguments.of("email@.i.com"),
                Arguments.of("email@i..com"),
                Arguments.of("email@i..sun.i.com"),
//                Arguments.of("short@0372.ua"),
//                Arguments.of("short@i.museum"),
//                Arguments.of("short@i-one.com"),
                Arguments.of("email@"),
                Arguments.of("email@.com."),
                Arguments.of("email@com."),
                Arguments.of("email@com.."),
                Arguments.of("email..@i.com"),
                Arguments.of("email@.i.com"),
                Arguments.of("email@..i.com"),
                Arguments.of("email@.i.com."),
                Arguments.of("email@..i.com."),
                Arguments.of("email@.i.com.."),
                Arguments.of("email@..i.com.."),
                Arguments.of("email@i@i.com"),
                Arguments.of("email@i.com@i.com"),
                Arguments.of("email@i.com@i.com@i.com"),
                Arguments.of("email@i@i@i.com"),
                Arguments.of("email@i@i@i@i.com"),
                Arguments.of("a".repeat(256)),
                Arguments.of("@i.com"),
                Arguments.of("a".repeat(255)),
                Arguments.of("i"),
                Arguments.of("i."),
                Arguments.of(".com"),
                // Invalid: Domain with special characters
                Arguments.of("long.email@i..com"),
//                Arguments.of("long.email@-i-.com"),
                Arguments.of("long.email@-i.+.com"),
                Arguments.of("long.email@i+.com"),
                Arguments.of("long.email@-i=.com"),
                Arguments.of("long.email@.i.com"),
                Arguments.of("long.email@,i,com"),
                Arguments.of("long.email@i,com"),
                Arguments.of("long.email@i>com"),
                Arguments.of("long.email@i?com"),
                Arguments.of("long.email@i/com"),
                Arguments.of("long.email@icom"),
                Arguments.of("missingdot@com"),
                Arguments.of("missingatgmail.com"),
                Arguments.of("invalid..domain@i.com"),
                Arguments.of("domain.com@i"),
                Arguments.of("domain@.com"),
                Arguments.of("domain@com."),
//                Arguments.of("domain@i-.com"),
//                Arguments.of("domain@-i.com"),
                Arguments.of("domain@.com"),
                Arguments.of("domain@i..com"),
                Arguments.of("domain@.i.com"),
                Arguments.of("domain@_i.com"),
                Arguments.of("domain@exa_mple.com"),
                Arguments.of("domain@i.c_om"),
//                Arguments.of("long.email@i-.com"),
//                Arguments.of("long.email@-i.com"),
                Arguments.of("long.email@i.com-"),
                Arguments.of("long.email@i.-com"),
                Arguments.of("long.email@i-.com."),
                Arguments.of("long.email@i.com."),
                Arguments.of("long.email@i..com."),
                Arguments.of("long.email@i.com.."),
                Arguments.of("long.email@i.-com."),
                Arguments.of("long.email@i-.com.."),
                Arguments.of("long.email@i.com.-"),
                Arguments.of("long.email@!i.com..-"),
                Arguments.of("long.email@@i..com"),
                Arguments.of("long.email@#i-.com"),
                Arguments.of("long.email@$i.com"),
                Arguments.of("long.email@%i.com-"),
                Arguments.of("long.email@^i.-com"),
                Arguments.of("long.email@*i-.com."),
                Arguments.of("long.email@(i.com."),
                Arguments.of("long.email@)i..com."),
                Arguments.of("long.email@_i.com.."),
                Arguments.of("long.email@+i.-com."),
                Arguments.of("long.email@<i-.com.."),
                Arguments.of("long.email@>i.com.-"),
                Arguments.of("long.email@>i.com..-"),
                Arguments.of("email@i..com"),
                Arguments.of("email@i@com"),
                Arguments.of("email@i@com."),
                Arguments.of("email@i.com."),
                Arguments.of("email@i.com.."),
                Arguments.of("email@i.com@"),
                Arguments.of("email@i.com@."),
                Arguments.of("email@i.com@.."),
                Arguments.of("email@i.com@com"),
                Arguments.of("email@i.com@com."),
                Arguments.of("email@i.com@com.."),
                Arguments.of("email@i.com@.com"),
                Arguments.of("email@i.com@..com"),
                Arguments.of("email@i.com@com.com"),
                Arguments.of("email@i.com@com.com."),
                Arguments.of("email@i.com@com.com.."),
                // Invalid: Missing username
                Arguments.of("@i.com"),
                // Invalid: Missing username with @
                Arguments.of("i..com"),
                Arguments.of("i-.com"),
                Arguments.of("-i.com"),
                Arguments.of("i.com-"),
                Arguments.of("i.-com"),
                Arguments.of("i-.com."),
                Arguments.of("i.com."),
                Arguments.of("i..com."),
                Arguments.of("i.com.."),
                Arguments.of("i.-com."),
                Arguments.of("i-.com.."),
                Arguments.of("i.com.-"),
                Arguments.of("i.com..-"),
                // Invalid: Missing domain
                Arguments.of("1234567890"),
                Arguments.of("123456789A"),
                Arguments.of("long..email"),
                Arguments.of(".long.email"),
                Arguments.of("long.email"),
                Arguments.of("long.email"),
                Arguments.of("long.email1"),
                Arguments.of("long.email.1"),
                Arguments.of("long.email.1."),
                Arguments.of("long.email..1"),
                Arguments.of("long.email.1.."),
                Arguments.of("long.email..1."),
                Arguments.of("long.email.1..2"),
                Arguments.of("long.email..1..2"),
                Arguments.of("long.email.1..2."),
                Arguments.of("long.email..1..2."),
                Arguments.of("long.email.1..2.."),
                Arguments.of("long.email..1..2.."),
                // Invalid: Missing @ symbol
                Arguments.of("invalid-email"),
                Arguments.of("noatsymbol.i.com"),
                Arguments.of("missingAtSymbol.com"),
                Arguments.of("missingAtSymbolNoDomain"),
                // Invalid: Missing domain
                Arguments.of("username@"),
                Arguments.of("username@."),
                Arguments.of("username@com"),
                // Invalid: Missing username
                Arguments.of("@domain.com"),
                Arguments.of("@domain"),
                Arguments.of("@domain."),
                Arguments.of("@.com"),
                Arguments.of("@.i"),
                // Invalid: Consecutive dots in username
                Arguments.of("user..name@i.com"),
                Arguments.of("user...name@i.com"),
                Arguments.of("user....name@i.com"),
                Arguments.of("user.....name@i.com"),
                Arguments.of("user......name@i.com"),
                // Invalid: Consecutive dots in domain
                Arguments.of("username@i..com"),
                Arguments.of("username@i...com"),
                Arguments.of("username@i..a..com"),
                Arguments.of("username@i..a..a.com"),
                Arguments.of("username@i..a..a..com"),
                // Invalid: Top-level domain less than two letters
                Arguments.of("username@i. "),
                // Invalid: Domain with less than two levels
                Arguments.of("username@e.e"),
                Arguments.of("username@e.e.e"),
                Arguments.of("username@e.."),
                Arguments.of("username@e..f"),
                Arguments.of("username@e.f."),
                // Invalid: Missing domain levels
                Arguments.of("username@i"),
                Arguments.of("username@i."),
                // Invalid: Top-level domain less than two letters
                Arguments.of("username@i.c"),
                // Combining both scenarios
                Arguments.of("username@.i"),
                Arguments.of("username@i.")
        );
    }
}
