package org.softserve.academy.provider;

import org.junit.jupiter.api.extension.ExtensionContext;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.ArgumentsProvider;

import java.util.stream.Stream;

public class InvalidEmailProvider
        implements ArgumentsProvider {
    @Override
    public Stream<? extends Arguments> provideArguments(ExtensionContext context) {
        return Stream.of(
                Arguments.of("email@"),
                Arguments.of("email@."),
                Arguments.of("email@i"),
                Arguments.of("email@i."),
                Arguments.of("email@ua"),
                Arguments.of("email@.i"),
                Arguments.of("email@i.."),
                Arguments.of("email@iua"),
                Arguments.of("email@.ua"),
                Arguments.of("email@i.u"),
                Arguments.of("email@i.u."),
                Arguments.of("email@1i.u"),
                Arguments.of("email@i@ua"),
                Arguments.of("email@i_ua"),
                Arguments.of("email@i-ua"),
                Arguments.of("email@i%ua"),
                Arguments.of("email@i&ua"),
                Arguments.of("email@i?ua"),
                Arguments.of("email@i/ua"),
                Arguments.of("email@i,ua"),
                Arguments.of("email@i;ua"),
                Arguments.of("email@i:ua"),
                Arguments.of("email@i'ua"),
                Arguments.of("email@i\\ua"),
                Arguments.of("email@i\"ua"),
                Arguments.of("email@i\tua"),
                Arguments.of("email@i\nua"),
                Arguments.of("email@i.u.a"),
                Arguments.of("email@i. ua"),
                Arguments.of("email@i..ua"),
                Arguments.of("email@i.ua."),
                Arguments.of("email@.i.ua"),
                Arguments.of("email@i+.ua"),
                Arguments.of("email@i.>ua"),
                Arguments.of("email@i.?ua"),
                Arguments.of("email@+i.ua"),
                Arguments.of("email@i.u1a"),
                Arguments.of("email@_i.ua"),
                Arguments.of("email@i.ua-"),
                Arguments.of("email@i.ua_"),
                Arguments.of("email@i.u_a"),
                Arguments.of("email@i.-ua"),
                Arguments.of("email@$i.ua"),
                Arguments.of("email@i..ua."),
                Arguments.of("email@i.ua.."),
                Arguments.of("email@i.ua.-"),
                Arguments.of("email@i.ua.0"),
                Arguments.of("email@@i..ua"),
                Arguments.of("email@#i-.ua"),
                Arguments.of("email@%i.ua-"),
                Arguments.of("email@^i.-ua"),
                Arguments.of("email@.i.ua."),
                Arguments.of("email@i@i.ua"),
                Arguments.of("email@i...ua"),
                Arguments.of("email@i.+.ua"),
                Arguments.of("email@..i.ua"),
                Arguments.of("email@. i.ua"),
                Arguments.of("email@.i. ua"),
                Arguments.of("email@..i.ua."),
                Arguments.of("email@*i-.ua."),
                Arguments.of("email@)i..ua."),
                Arguments.of("email@_i.ua.."),
                Arguments.of("email@+i.-ua."),
                Arguments.of("email@.i.ua.."),
                Arguments.of("email@>i.ua.-"),
                Arguments.of("missingdot@ua"),
                Arguments.of("email@..i.ua.."),
                Arguments.of("email@<i-.ua.."),
                Arguments.of("email@>i.ua..-"),
                Arguments.of("email@!i.ua..-"),
                Arguments.of("email@i@i@i.ua"),
                Arguments.of("email@i..a..ua"),
                Arguments.of("email@i.ua@i.ua"),
                Arguments.of("email@i@i@i@i.ua"),
                Arguments.of("email@i..a..a.ua"),
                Arguments.of("email@i..a..a..ua"),
                Arguments.of("missingatgmail.ua"),
                Arguments.of("email@ixa_mple.ua"),
                Arguments.of("email@i..sun.i.ua"),
                Arguments.of("invalid..email@i.ua"),
                Arguments.of("email@i.ua@i.ua@i.ua"),
                Arguments.of("email@123.123.123.123"),
                Arguments.of("email@111.222.333.44444"),
                Arguments.of("email..@i.ua"),
                Arguments.of("email.ua@i"),
                Arguments.of("email[@i.ua"),
                Arguments.of("email]@i.ua"),
                Arguments.of("email,@i.ua"),
                Arguments.of("email)@i.ua"),
                Arguments.of("email<@i.ua"),
                Arguments.of("email:@i.ua"),
                Arguments.of("email>@i.ua"),
                Arguments.of("email\t@i.ua"),
                Arguments.of("email:@i.ua"),
                Arguments.of("email;@i.ua"),
                Arguments.of("email:@i.ua"),
                Arguments.of("email@@i.ua"),
                Arguments.of("email 123@i.ua"),
                Arguments.of("email.email@ua"),
                Arguments.of("email.email@ix.c"),
                Arguments.of("email.email@.ua"),
                Arguments.of("email.i.ua"),
                Arguments.of(".email@i.ua"),
                Arguments.of("email email@i.ua"),
                Arguments.of("Abc..123@i.ua"),
                Arguments.of("email@127.0.0.1"),
                Arguments.of(".email@i.ua"),
                Arguments.of(".abc@i.ua"),
                Arguments.of("@i.ua"),
                Arguments.of("abc.@i.ua"),
                Arguments.of(".abc@i.ua"),
                Arguments.of("longemail.@i.ua"),
                Arguments.of("123longemail.@i.ua"),
                Arguments.of("longemail123.@i.ua"),
                Arguments.of("email..email@i.ua"),
                Arguments.of("email...email@i.ua"),
                Arguments.of(" "),
                Arguments.of(" @i.ua"),
                Arguments.of("a@ .ua"),
                Arguments.of("a".repeat(256)),
                Arguments.of("@i.ua"),
                Arguments.of("a".repeat(255)),
                Arguments.of("i"),
                Arguments.of("i."),
                Arguments.of(".ua"),
                Arguments.of("@i.ua"),
                Arguments.of("@imail@i.ua"),
                Arguments.of(")email@i.ua"),
                Arguments.of("[email@i.ua"),
                Arguments.of("]email@i.ua"),
                Arguments.of(",email@i.ua"),
                Arguments.of("<email@i.ua"),
                Arguments.of(".email@i.ua"),
                Arguments.of(">email@i.ua"),
                Arguments.of(":email@i.ua"),
                Arguments.of("\"email@i.ua"),
                Arguments.of(":email@i.ua"),
                Arguments.of(";email@i.ua"),
                Arguments.of(":email@i.ua"),
                Arguments.of("user123@i.i123"),
                Arguments.of("i..ua"),
                Arguments.of("i-.ua"),
                Arguments.of("-i.ua"),
                Arguments.of("i.ua-"),
                Arguments.of("i.-ua"),
                Arguments.of("i-.ua."),
                Arguments.of("i.ua."),
                Arguments.of("i..ua."),
                Arguments.of("i.ua.."),
                Arguments.of("i.-ua."),
                Arguments.of("i-.ua.."),
                Arguments.of("i.ua.-"),
                Arguments.of("i.ua..-"),
                // Invalid: Missing email
                Arguments.of("1234567890"),
                Arguments.of("123456789A"),
                Arguments.of("long..email"),
                Arguments.of(".email"),
                Arguments.of("email"),
                Arguments.of("email"),
                Arguments.of("email1"),
                Arguments.of("email.1"),
                Arguments.of("email.1."),
                Arguments.of("email..1"),
                Arguments.of("email.1.."),
                Arguments.of("email..1."),
                Arguments.of("email.1..2"),
                Arguments.of("email..1..2"),
                Arguments.of("email.1..2."),
                Arguments.of("email..1..2."),
                Arguments.of("email.1..2.."),
                Arguments.of("email..1..2.."),
                // Invalid: Missing @ symbol
                Arguments.of("invalid-email"),
                Arguments.of("noatsymbol.i.ua"),
                Arguments.of("missingAtSymbol.ua"),
                Arguments.of("missingAtSymbolNoemail"),
                // Invalid: Missing email
                Arguments.of("@email.ua"),
                Arguments.of("@email"),
                Arguments.of("@email."),
                Arguments.of("@.ua"),
                Arguments.of("@.i"),
                // Invalid: Consecutive dots in email
                Arguments.of("user..name@i.ua"),
                Arguments.of("user...name@i.ua"),
                Arguments.of("user....name@i.ua"),
                Arguments.of("user.....name@i.ua"),
                Arguments.of("user......name@i.ua")
                // Invalid: email with special characters
//                Arguments.of("email@-i-.ua"),
//                Arguments.of("email@i-.ua"),
//                Arguments.of("email@-i.ua"),
//                Arguments.of("email@i-.ua"),
//                Arguments.of("email@-i.ua"),
//                Arguments.of("email@[123.123.123.123]"),
//                Arguments.of("email\n@i.ua"),
//                Arguments.of("short@0372.ua"),
//                Arguments.of("short@i.museum"),
//                Arguments.of("short@i-one.ua"),
//                Arguments.of("1234567890@host.ua"),
//                Arguments.of("1abc@i.ua"),
//                Arguments.of("abc!@i.ua"),
//                Arguments.of("1abc@i.ua"),
//                Arguments.of("abc@i1.ua"),
//                Arguments.of("abc@doma1n.ua"),
//                Arguments.of("a@b.co"),
//                Arguments.of("abcdeabcdeabcdeabcdea@email.ua"),
//                Arguments.of("1email@.ua."),
//                Arguments.of("1mail@i.ua"),
//                Arguments.of("mail1@i.ua"),
//                Arguments.of("now.1@i.ua"),
//                Arguments.of("!email@i.ua"),
//                Arguments.of("e@i.ua"),
//                Arguments.of("+email@i.ua"),
//                Arguments.of("-email@i.ua"),
//                Arguments.of("&email@i.ua"),
//                Arguments.of("*email@i.ua"),
//                Arguments.of("_email@i.ua"),
//                Arguments.of("+email@i.ua"),
//                Arguments.of("email@1.ua"),
//                Arguments.of("email@11.ua"),
//                Arguments.of("123@i.ua"),
//                Arguments.of("email@-i.ua"),
//                Arguments.of("email+tag@i.ua"),
//                Arguments.of("email@i-.ua"),
//                Arguments.of("_______@i.ua"),
//                Arguments.of("email@-i.ua"),
//                Arguments.of("email@i-.ua"),
//                Arguments.of("email+@i.ua"),
//                Arguments.of("email&@i.ua"),
//                Arguments.of("email*@i.ua"),
//                Arguments.of("email_@i.ua"),
//                Arguments.of("email@i.12"),
//                Arguments.of("!email@i.ua"),
//                Arguments.of("#email@i.ua"),
//                Arguments.of("$email@i.ua"),
//                Arguments.of("%email@i.ua"),
//                Arguments.of("^email@i.ua"),
//                Arguments.of("=email@i.ua"),
//                Arguments.of("{email@i.ua"),
//                Arguments.of("}email@i.ua"),
//                Arguments.of("/email@i.ua"),
//                Arguments.of("|email@i.ua"),
//                Arguments.of("'email@i.ua"),
//                Arguments.of("\nemail@i.ua"),
//                Arguments.of("email/@i.ua"),
//                Arguments.of("email|@i.ua"),
//                Arguments.of("\temail@i.ua"),
//                Arguments.of("email'@i.ua"),
//                Arguments.of("user-123@i.ua"),
//                Arguments.of("user_123@i.ua"),
//                Arguments.of("firstname+lastname@i.ua"),
//                Arguments.of("firstname-lastname@i.ua"),
//                Arguments.of("verylongemailaddresswithmorethan30charactersinlocalpart@i.ua"),
//                // Invalid: email with short length
//                Arguments.of("email!@i.ua"),
//                Arguments.of("email$@i.ua"),
//                Arguments.of("email%@i.ua"),
//                Arguments.of("email^@i.ua"),
//                Arguments.of("email=@i.ua"),
//                Arguments.of("email{@i.ua"),
//                Arguments.of("email}@i.ua"),
//                Arguments.of("email#@i.ua"),
        );
    }
}
