name: Running Tests

on: [push]

permissions:
  contents: write
  pages: write
  id-token: write
  actions: read
  checks: write

jobs:
  build:
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-22.04, ubuntu-latest ] # macos-latest  windows-latest ubuntu-20.04

    runs-on: ${{ matrix.os }}

    steps:

      - name: Clone code from repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Python script generator emails
        run: |
          cd src/test/resources
          python generator_emails.py
          cd ../../..

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Attach screenshots and reports
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: screenshots-and-report
          path: |
            screenshots/
            **/surefire-reports/emailable-report.html
            tracing/
            video/

      - name: Dorny Test Reporter
        uses: dorny/test-reporter@v1.9.1
        if: success() || failure()
        with:
          name: Test Report for ${{ matrix.os }}
          path: target/surefire-reports/TEST-*.xml
          reporter: java-junit

  check-java-code-style:
    name: Check Java code style

    runs-on: ubuntu-latest

    steps:
      - name: Clone code from repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run java checkstyle
        uses: nikitasavinov/checkstyle-action@0.6.0
