name: Java CI with Maven

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

permissions:
  contents: write
  pages: write
  id-token: write
  actions: read
  checks: write

jobs:
  Test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    services:
      postgres:
        image: postgres

        env:
          POSTGRES_PASSWORD: mypass
          POSTGRES_USER: myuser
          POSTGRES_DB: example

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - run: |
          sudo apt-get update && sudo apt-get install --yes --no-install-recommends postgresql-client
      - run: |
          psql -h localhost -U myuser -d example -c '
            CREATE TABLE categories (
              id bigserial PRIMARY KEY,
              avatar varchar NOT NULL,
              title varchar NOT NULL UNIQUE
            );
            CREATE TABLE club (
              id bigserial PRIMARY KEY,
              title varchar NOT NULL,
              description varchar NOT NULL,
              image_url varchar,
              category_id int8 REFERENCES categories(id)
            );
            CREATE TABLE child (
              id bigserial PRIMARY KEY,
              first_name varchar NOT NULL,
              last_name varchar NOT NULL,
              birth_date date
            );
            CREATE TABLE club_child (
              club_id int8 REFERENCES club(id),
              child_id int8 REFERENCES child(id)
            );
          '
        env:
          PGPASSWORD: mypass
      

      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Test with Maven
        run: mvn clean test

      - name: Generate JaCoCo Report
        run: mvn jacoco:report
        if: success() || failure()

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: '**/target/surefire-reports/TEST-*.xml'
        if: success() || failure()

      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: '**/target/site/jacoco/'
        if: success() || failure()


  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Attach screenshots and reports
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: screenshots-and-report
          path: |
            screenshots/
            **/surefire-reports/emailable-report.html
            tracing/
            video/

      - name: Dorny Test Reporter
        uses: dorny/test-reporter@v1.9.1
        if: success() || failure()
        with:
          name: Test Report for ${{ matrix.os }}
          path: target/surefire-reports/TEST-*.xml
          reporter: java-junit

  check-java-code-style:
    name: Check Java code style

    runs-on: ubuntu-latest

    steps:
      - name: Clone code from repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run java checkstyle
        uses: nikitasavinov/checkstyle-action@master
        with:
          checkstyle_config: 'check.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: 'github-pr-check'
          tool_name: 'Checkstyle'